# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
