# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='item_link',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='item_short_descr',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='item_title',
        ),
    ]
