# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Arts',
        ),
    ]
