# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181128_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
