# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181128_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arts',
            new_name='Art',
        ),
    ]
