# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181128_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
