# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181128_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
