# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181128_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='is_pub',
        ),
    ]
