# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181127_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link_photo',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
