# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_link_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
