# Generated by Django 2.1.3 on 2018-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_pic', verbose_name='Фото'),
        ),
    ]
