# Generated by Django 2.1.3 on 2018-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181128_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='author_name',
            new_name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='main.Category'),
        ),
    ]
