# Generated by Django 2.1.3 on 2018-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181128_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='category',
        ),
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
