# Generated by Django 2.1.3 on 2018-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='poems', to='main.Category'),
        ),
    ]
