# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Domain', to_field='url'),
        ),
    ]
