# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_htmlsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='htmlSource',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
